const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../../.env") });
require("./index");
const { Category, Service, Car, Price } = require("./models");

let services = {
  "Motor qismini ta'mirlash": [
    {
      name: "Motor kapital ta'mirlash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Injektor tozalash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Galovka ta'mirlash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Klapan reglurovka",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Moy almashtirish",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Boshqa motor nosozligini ta'mirlash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  "Yurish qismini ta'mirlash": [
    {
      name: "Amartizator ta'mirlash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Tormoz tizimini ta'mirlash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Rulavoy qismini ta'mirlash",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Boshqa xizmatlar kelishilgan narxda",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  Avtoelektrik: [
    {
      name: "Xizmatga qarab kelishilgan narxda",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  "Kuzov ta'mirlash": [
    {
      name: "Polirovka keramika",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Shumalyatsiya",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Vakuumlik xizmati",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  Vulkanizatsiya: [
    {
      name: "Xizmatga qarab kelishilgan narxda",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  Razval: [
    {
      name: "Old g'ildiraklar",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Komplekt g'ildiraklar",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  "Gaz ustanovka": [
    {
      name: "Propan - 45 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Propan - 80 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Propan - 90 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Propan - 100 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Metan - 45 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Metan - 80 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Metan - 90 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Metan - 100 balon",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
  Avtomoyka: [
    {
      name: "O'z-o'ziga xizmat",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Sirt qismini yuvdirish",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Faqat salon qismi",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
    {
      name: "Polniy moyka ximchistki",
      cars: {
        Kaptiva: "$100",
        Malibu: "$100",
        Gentra: "$100",
        Cobalt: "$100",
        "Nexia 3": "$100",
        "Nexia 2": "$100",
        "Nexia 1": "$100",
        Damas: "$100",
        Spark: "$100",
        Matiz: "$100",
        Tiko: "$100",
        Lacetti: "$100",
      },
    },
  ],
};

(async () => {
  // remove existing collections
  await Category.deleteMany();
  await Service.deleteMany();
  await Car.deleteMany();
  await Price.deleteMany();

  // insert categories and services
  for (let category of Object.keys(services)) {
    let newCategory = await new Category({ name: category }).save();

    for (let service of services[category]) {
      // create service
      const newService = await new Service({
        name: service.name,
        category: newCategory._id,
      }).save();
      let cars = service.cars || [];
      for (let car of Object.keys(cars)) {
        // create cars if doesn't exist
        let newCar = await Car.findOne({ name: car });
        if (!newCar) {
          newCar = await new Car({ name: car }).save();
        }
        // create prices
        await new Price({
          car: newCar._id,
          service: newService._id,
          category: newCategory._id,
          value: cars[car],
        }).save();
      }
    }
  }

  console.log("All done!");
  process.exit(0);
})();
